class FrenchMen 
{
	class FirstNames 
	{
		michel = "Michel";
		michel1 = "Michel";
		michel2 = "Michel";
		jean = "Jean";
		jean1 = "Jean";
		jean2 = "Jean";
		hector = "Hector";
		alain = "Álvaro";
		baptiste = "Baptiste";
		martin = "Martin";
		jacques = "Jacques";
		hugo = "Hugo";
		emile = "Emile";
		ruben = "Ruben";
		jean_baptiste = "Jean-Baptiste";
		manuel = "Manuel";
		alphonse = "Alphonse";
		christian = "Cristian";
		julien = "Julien";
		vicent = "Vicent";
		jean_paul = "Jean-Paul";
		fabien = "Fabien";
		raoul = "Raoul";
		camille = "Camille";
		joseph = "Joseph";
		joseph1 = "Joseph";
		joseph2 = "Joseph";
		jean_philippe = "Jean-Philippe";
		charles = "Charles";
		charles1 = "Charles";
		charles2 = "Charles";
		antoine = "Antoine";
		antoine1 = "Antoine";
		gustave = "Gustave";
		guy = "Guy";
		guy1 = "Guy";
		luc = "Luc";
		sebastien = "Sebastien";
		napoleon = "Napoleon";
		napoleon2 = "Napoleon";
		jean_pierre = "Jean-Pierre";
		jean_pierre1 = "Jean-Pierre";
		jean_pierre2 = "Jean-Pierre";
		pierre = "Pierre";
		pierre1 = "Pierre";
		pierre2 = "Pierre";
	};

	class LastNames 
	{
		le_goff = "Le Goff";
		carpentier = "Carpentier";
		klein = "Klein";
		dupuy = "Dupuy";
		clement = "Clement";
		gaillard = "Gaillard";
		caron = "Caron";
		renard = "Renard";
		leclerc = "Leclerc";
		martins = "Martins";
		velazquez = "Velazquez";
		pascal = "Pascal";
		olivier = "Olivier";
		guerrier = "Guerrier";
		navarre = "Navarre";
		chevallier = "Chevallier";
		payet = "Payet";
		pierre = "Pierre";
		pierre1 = "Pierre";
		pierre2 = "Pierre";
		sanchez = "Sanchez";
		martinez = "Martinez";
		garcia = "Garcia";
		martin = "Martin";
		martin1 = "Martin";
		martin2 = "Martin";
		etienne = "Etienne";
		bernard = "Bernard";
		robert = "Robert";
		etienne1 = "Etienne";
		bernard1 = "Bernard";
		robert1 = "Robert";
		simon = "Simon";
		lambert = "Lambert";
		durand = "Durand";
		dubois = "Dubois";
		leonard = "Leonard";
		betancourt = "Betancourt";
		laurent = "Laurent";
		mercier = "Mercier";
		garnier = "Garnier";
		richard = "Richard";
		richard1 = "Richard";
		richard2 = "Richard";
	};
};