class GenericNames 
{
	class LatinoMen 
	{
		class FirstNames 
		{
			che = "Che";
			miguel = "Miguel";
			miguel1 = "Miguel";
			miguel2 = "Miguel";
			juan = "Juan";
			juan1 = "Juan";
			juan2 = "Juan";
			hector = "Hector";
			alvaro = "Álvaro";
			benito = "Benito";
			martin = "Martín";
			diego = "Diego";
			hugo = "Hugo";
			emilio = "Emilio";
			ruben = "Ruben";
			horacio = "Horacio";
			manuel = "Manuel";
			alfonso = "Alfonso";
			christian = "Cristian";
			julio = "Julio";
			vicente = "Vicente";
			jimmy = "Jimmy";
			fidel = "Fidel";
			raul = "Raul";
			camilo = "Camilo";
			jose = "José";
			jose1 = "José";
			jose2 = "José";
			ernesto = "Ernesto";
			carlos = "Carlos";
			carlos1 = "Carlos";
			carlos2 = "Carlos";
			antonio = "Antonio";
			antonio1 = "Antonio";
			gustavo = "Gustavo";
			guillermo = "Guillermo";
			guillermo1 = "Guillermo";
			luca = "Luca";
			sebastian = "Sebastián";
			nicolas = "Nicolás";
			nicolas2 = "Nicolás";
			vladimir = "Vladimir";
			ivan = "Iván";
			javier = "Javier";
			javier1 = "Javier";
			javier2 = "Javier";
			pedro = "Pedro";
			pedro1 = "Pedro";
			pedro2 = "Pedro";
			yunior = "Yunior";
			yulieski = "Yulieski";
		};

		class LastNames 
		{
			gil = "Gil";
			carracedo = "Carracedo";
			candas = "Candás";
			segura = "Segura";
			castro = "Castro";
			guevara = "Guevara";
			cienfuegos = "Cienfuegos";
			rodriguez = "Rodríguez";
			gonzalez = "González";
			marti = "Martí";
			velazquez = "Velazquez";
			pascal = "Pascal";
			ocasio = "Ocásio";
			guerrero = "Guerrero";
			navarro = "Navarro";
			cotilla = "Cotilla";
			correa = "Correa";
			ordunez = "Ordúñez";
			perez = "Pérez";
			perez1 = "Pérez";
			perez2 = "Pérez";
			sanchez = "Sánchez";
			sanchez1 = "Sánchez";
			sanchez2 = "Sánchez";
			martinez = "Martínez";
			martinez1 = "Martínez";
			garcia = "García";
			garcia1 = "García";
			garcia2 = "García";
			jimenez = "Jiménez";
			martin = "Martín";
			martin1 = "Martín";
			martin2 = "Martín";
			iglesias = "Iglesia";
			diaz = "Díaz";
			rosario = "Rosário";
			iglesias1 = "Iglesia";
			diaz1 = "Díaz";
			rosario1 = "Rosário";
			santana = "Santana";
			de_la_cruz = "De la Cruz";
			santos = "Santos";
			pena = "Peña";
			burgos = "Burgos";
			reyes = "Reyes";
			de_leon = "De León";
			leon = "León";
			betancourt = "Betancourt";
			cruz = "Cruz";
			ramos = "Ramos";
			lavoe = "Lavoe";
			morales = "Morales";
			morales1 = "Morales";
			morales2 = "Morales";
		};
	};
};