class C_man_p_beggar_F;
class C_man_p_fugitive_F;
class C_man_p_shorts_1_F;
class C_man_1;
class C_man_1_1_F;
class C_man_1_2_F;
class C_man_1_3_F;
class C_man_casual_1_F;
class C_man_casual_2_F;
class C_man_casual_3_F;
class C_man_casual_4_F;
class C_man_casual_5_F;
class C_man_casual_6_F;
class C_man_sport_1_F;
class C_man_sport_2_F;
class C_man_sport_3_F;
class C_man_polo_1_F;
class C_man_polo_2_F;
class C_man_polo_3_F;
class C_man_polo_4_F;
class C_man_polo_5_F;
class C_man_polo_6_F;
class C_man_shorts_1_F;
class C_man_shorts_2_F;
class C_man_shorts_3_F;
class C_man_shorts_4_F;
class C_man_hunter_1_F;
class C_journalist_F;
class C_man_pilot_F;
class C_scientist_F;
class C_man_w_worker_F;
class C_man_Fisherman_01_F;

class 7r_civ_1 : C_man_p_beggar_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_2 : C_man_p_fugitive_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_3 : C_man_p_shorts_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_4 : C_man_1 {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_5 : C_man_1_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_6 : C_man_1_2_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_7 : C_man_1_3_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_8 : C_man_casual_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_9 : C_man_casual_2_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_10 : C_man_casual_3_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_11 : C_man_Fisherman_01_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_12 : C_man_casual_4_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_13 : C_man_casual_5_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_14 : C_man_casual_6_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_15 : C_man_sport_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_16 : C_man_sport_2_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_17 : C_man_sport_3_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_18 : C_man_polo_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_19 : C_man_polo_2_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_20 : C_man_polo_3_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_21 : C_man_polo_4_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_22 : C_man_polo_5_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_23 : C_man_polo_6_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_24 : C_man_shorts_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_25 : C_man_shorts_2_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_26 : C_man_shorts_3_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_27 : C_man_shorts_4_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_28 : C_man_hunter_1_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_29 : C_journalist_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_30 : C_man_pilot_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_31 : C_scientist_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};
class 7r_civ_32 : C_man_w_worker_F {identityTypes[] = {"Head_Latino","LanguageFRE_F","G_CIVIL_male"}; editorSubcategory = "EdSubcat_Civ_Latino"; GenericNames = "LatinoMen"; scope = 2; scopeArsenal = 2; scopeCurator = 2;};